site_name: Argo CD - Declarative GitOps CD for Kubernetes
repo_url: https://github.com/AlphaLabsUY/rtd-alpha-docs
strict: true
theme:
  name: material
  palette:
    primary: teal
  font:
    text: 'Work Sans'
  logo: 'assets/logo.png'
  favicon: 'assets/favicon.png'
  # language: en-custom
  custom_dir: overrides
extra_javascript:
- assets/versions.js
extra_css:
- assets/versions.css
google_analytics:
- 'UA-105170809-2'
- 'auto'
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
  - Overview: index.md
  - Support: SUPPORT.md
  - roadmap.md
  - Releases ⧉: https://github.com/argoproj/argo-cd/releases
  - Blog ⧉: https://blog.argoproj.io/
